-----BEGIN CERTIFICATE-----
MIIGEzCCBPugAwIBAgIQbDTjHHxe8kqywTzEMyce2zANBgkqhkiG9w0BAQsFADCB
ijELMAkGA1UEBhMCUEwxIjAgBgNVBAoMGVVuaXpldG8gVGVjaG5vbG9naWVzIFMu
QS4xJzAlBgNVBAsMHkNlcnR1bSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEuMCwG
A1UEAwwlQ2VydHVtIERpZ2l0YWwgSWRlbnRpZmljYXRpb24gQ0EgU0hBMjAeFw0y
MjA2MjAyMTMyMDNaFw0yMzA2MjAyMTMyMDJaMEwxITAfBgNVBAMMGHNob3BAbWVu
bnlzYmFzdGVsc2hvcC5kZTEnMCUGCSqGSIb3DQEJARYYc2hvcEBtZW5ueXNiYXN0
ZWxzaG9wLmRlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwS7Bc/xU
g/WMHCSFQRRMZ3b43+fHxIh+IN82LU1Uht5ldJjvuDspRrMwX8zTpXJle60DRPo0
TmgBl7BIxd0NDNx6gHuhUgZ3XUbzJcuexYP5qR+2FlLSuS5r0UMxAevOgYOxFdYL
gqOEWusNId1sZMQIb8azO8k09ki5pcnaFY7WNhZQas0YuKfLkuebl+F3fGprRjM+
jj55RzS8KY8tcZ1UbcJCdcM0Zeho3q9G0071TsgbyCb6QoLOqZ7+1/T5+Jefrvnb
QirqppcxxhqguqMjoaLvu/LIxqKNJzTSr0lCUEAgqbxhHSWALrnRlMnwSPCtbX99
3XAFbJVShAY+emxveb0IX8mXuhbdEMIMqyC4JH+t7ersx0xqlvWRsNY0z/aZofp3
xuXm6ALz0M5oMSQv3gvX7snZc+9P/8KWIht6Xtl62pqBUQzi/u/Jk0vmmd4lSs9v
Qkiq6iEttDlzOxJ3O5z0AamWpQlAlr+B152IzLQKDVRFN81npZK6Jt7RBawqTobP
SiDBbubgNf8A7zL5LCwUd4bfimpEUnLyK5IHGTOZ7seIjhj3IIEFeHXfwZbtPEEd
nGqOXfvIltzZeXKj++XbyOFdfMNkWsg2gsKYXOB4qtf7pa6+RFhaybBoUjFjno9W
PBGfA98OsXo4LdyOf7j92LgQ8s5WbzG/Hj8CAwEAAaOCAbAwggGsMAwGA1UdEwEB
/wQCMAAwMgYDVR0fBCswKTAnoCWgI4YhaHR0cDovL2NybC5jZXJ0dW0ucGwvZGlj
YXNoYTIuY3JsMHEGCCsGAQUFBwEBBGUwYzArBggrBgEFBQcwAYYfaHR0cDovL2Rp
Y2FzaGEyLm9jc3AtY2VydHVtLmNvbTA0BggrBgEFBQcwAoYoaHR0cDovL3JlcG9z
aXRvcnkuY2VydHVtLnBsL2RpY2FzaGEyLmNlcjAfBgNVHSMEGDAWgBQ/yljq8ckJ
fm4zwSOtTq0+PWxFpzAdBgNVHQ4EFgQU9rru/BDzHzFekVKjqjYTUGo2uvwwHQYD
VR0SBBYwFIESZGljYXNoYTJAY2VydHVtLnBsMEIGA1UdIAQ7MDkwNwYMKoRoAYb2
dwIFAQYMMCcwJQYIKwYBBQUHAgEWGWh0dHBzOi8vd3d3LmNlcnR1bS5wbC9DUFMw
HQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMA4GA1UdDwEB/wQEAwIEsDAj
BgNVHREEHDAagRhzaG9wQG1lbm55c2Jhc3RlbHNob3AuZGUwDQYJKoZIhvcNAQEL
BQADggEBAEhBJleNODDYiET02szN6OW45pnNx/FFR8sKr0FL1vOujNvHjzENyf2z
cGXcDlsVrqnyk/0CbVHM7glbb5qCDKun6NjCnebZ1iovgT770vTalol+TPmAwp6U
pA9QAdSA3bB/f8q4rdRtPKth+nGQqmDAjb1/hlXzJnlHLGe4K0CqPvJ8ayIjui6G
umSaWVLG3V/xWLQjVN2X03Kz5GwjNlI/3ZCH+YcUQg1m3NME2SMiwaa/q3U1K2Vl
a2eNGxxmjXqH8Bvx78PfQTqD4C6Osk4NR7kaMK7/KME6sLg/ybWLE8K5oBhRXKNg
hdpGj08Whjfp7XG1QwFJ4CgkVGqiwag=
-----END CERTIFICATE-----
node_path,validator,severity,code,message
certificate.tbsCertificate.extensions.4.extnValue.subjectKeyIdentifier,SubjectKeyIdentifierValidator,INFO,pkix.subject_key_identifier_method_1_identified,
certificate.tbsCertificate.extensions.6.extnValue.certificatePolicies,RequiredPolicyIdentifierValidator,ERROR,cabf.smime.no_required_reserved_policy_oid,Required policy OID 2.23.140.1.5.1.3 is missing
certificate.tbsCertificate.extensions.6.extnValue.certificatePolicies.0,CertificatePolicyQualifierValidator,NOTICE,pkix.certificate_policies_policy_has_qualifier,
certificate.tbsCertificate.extensions.7.extnValue.extKeyUsageSyntax,AllowedExtendedKeyUsageValidator,ERROR,cabf.smime.prohibited_eku_present,Prohibited EKU(s) present: 1.3.6.1.5.5.7.3.2
certificate.tbsCertificate.extensions.8.extnValue.keyUsage,AllowedKeyUsageValidator,ERROR,cabf.smime.prohibited_ku_present,Prohibited KUs present: dataEncipherment

