-----BEGIN CERTIFICATE-----
MIIGVzCCBT+gAwIBAgIRAJQzAI4OoCeRALh5UbmCVGMwDQYJKoZIhvcNAQELBQAw
gZcxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMT0wOwYD
VQQDEzRDT01PRE8gUlNBIENsaWVudCBBdXRoZW50aWNhdGlvbiBhbmQgU2VjdXJl
IEVtYWlsIENBMB4XDTE3MTIwMTAwMDAwMFoXDTIwMTEzMDIzNTk1OVowggFYMQsw
CQYDVQQGEwJHQjEPMA0GA1UEERMGTTUgM0VRMRswGQYDVQQIExJHcmVhdGVyIE1h
bmNoZXN0ZXIxEzARBgNVBAcTCk1hbmNoZXN0ZXIxEDAOBgNVBAkTB1NhbGZvcmQx
JjAkBgNVBAkTHU9mZmljZSBWaWxsYWdlLCBFeGNoYW5nZSBRdWF5MR8wHQYDVQQJ
ExYzcmQgRmxvb3IsIEJ1aWxkaW5nIDI2MRYwFAYDVQQKEw1Db21vZG8gQ0EgTHRk
MTMwMQYDVQQLEypJc3N1ZWQgdGhyb3VnaCBDb21vZG8gQ0EgTHRkIEUtUEtJIE1h
bmFnZXIxHzAdBgNVBAsTFkNvcnBvcmF0ZSBTZWN1cmUgRW1haWwxFDASBgNVBAMT
C1JvYmluIEFsZGVuMScwJQYJKoZIhvcNAQkBFhhyb2Jpbi5hbGRlbkBjb21vZG9j
YS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDL4uF88bi+bWmA
HyJ/ag4AoW5i1XY9ucaLyQFUCaitjQhFrrLN34iloXg7U+hBK7hm0bawTqEabMPk
q7ivd76kHLEiqZhhz8rGNbd/DF+up5X1KYQFVJl04YM8QzRMkqcQ4+QciYFqhZ0R
vHOKeV+DV3awPiJd4RH0q/3UuL0xBb78gE6pZT+S6crvM7eyDx/Aaz9rnO0wDR8y
J9RuToXGi6oEYSz0eAvdu3/oX04wU3C+0g2yyFTTYLOhycis5cPmFogiFq8qGWKX
CU9KpKMEWdLzWz9aWPJaHPeR0MJ2G6vyEMw7sNVE3gS1+FnuGT54ye6xxz0CXd2d
IWwSKbXlAgMBAAGjggHYMIIB1DAfBgNVHSMEGDAWgBSCr2yM+MX+lmF86B89K3FI
XsSLwDAdBgNVHQ4EFgQUMABYMHkLmQC8qnPjAF9wxd3DNBQwDgYDVR0PAQH/BAQD
AgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwQGCCsGAQUFBwMC
MEYGA1UdIAQ/MD0wOwYMKwYBBAGyMQECAQMFMCswKQYIKwYBBQUHAgEWHWh0dHBz
Oi8vc2VjdXJlLmNvbW9kby5uZXQvQ1BTMFoGA1UdHwRTMFEwT6BNoEuGSWh0dHA6
Ly9jcmwuY29tb2RvY2EuY29tL0NPTU9ET1JTQUNsaWVudEF1dGhlbnRpY2F0aW9u
YW5kU2VjdXJlRW1haWxDQS5jcmwwgYsGCCsGAQUFBwEBBH8wfTBVBggrBgEFBQcw
AoZJaHR0cDovL2NydC5jb21vZG9jYS5jb20vQ09NT0RPUlNBQ2xpZW50QXV0aGVu
dGljYXRpb25hbmRTZWN1cmVFbWFpbENBLmNydDAkBggrBgEFBQcwAYYYaHR0cDov
L29jc3AuY29tb2RvY2EuY29tMCMGA1UdEQQcMBqBGHJvYmluLmFsZGVuQGNvbW9k
b2NhLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAXWCKDAKp/KnAp+POMF4VFmWJuakT
QitqP0JTkOIZjMB0PR6YRWSEMwmlqJf2JuGqverNrIO4aKGSx3uqFjaj50b3vMOs
0pbKrFrmCbhh+X1HvYVDAlHkAx2swQC+s4ksYT7BY2IGnm/I46MPx4O1bngekgUw
SejdKp9uSTQ5QP6gcv4GmOvIPV+HB6UZp0rlR1AHNac+ZCqwW+ZSGYoEVGEjv1MN
Bp/XG5MgyYaJBlvrjfAhprIpe+DIhU4/+Yet49YfRXM2qgs4FfIrKyf57HSwsIzA
dZAtkJAwtCy13ul+r6Cq/asKKEtuGObi42HyJmT/kYg7xQIn46V1PofamQ==
-----END CERTIFICATE-----
node_path,validator,severity,code,message
certificate.tbsCertificate.validity.notBefore,ValidityPeriodRangeValidator,ERROR,cabf.smime.certificate_validity_period_exceeds_825_days,"Validity period of 1096 days, 0:00:00 exceeds maximum value of relativedelta(days=+825)"
certificate.tbsCertificate.subject.rdnSequence,SubscriberSubjectValidator,ERROR,cabf.smime.missing_required_attribute,Missing required attribute: 2.5.4.97
certificate.tbsCertificate.subject.rdnSequence,SubscriberSubjectValidator,ERROR,cabf.smime.missing_required_attribute,"Missing one of these required attributes: 2.5.4.4, 2.5.4.42, 2.5.4.65"
certificate.tbsCertificate.subject.rdnSequence,SubscriberSubjectValidator,ERROR,cabf.smime.prohibited_attribute,Prohibited attribute: 2.5.4.9
certificate.tbsCertificate.subject.rdnSequence,SubscriberSubjectValidator,ERROR,cabf.smime.prohibited_attribute,Prohibited attribute: 2.5.4.17
certificate.tbsCertificate.subject.rdnSequence.10.0.value.x520CommonName,CommonNameValidator,ERROR,cabf.smime.common_name_value_unknown_source,"Unknown CN value source: ""Robin Alden"""
certificate.tbsCertificate.extensions.1.extnValue.subjectKeyIdentifier,SubjectKeyIdentifierValidator,INFO,pkix.subject_key_identifier_method_1_identified,
certificate.tbsCertificate.extensions.4.extnValue.extKeyUsageSyntax,AllowedExtendedKeyUsageValidator,ERROR,cabf.smime.prohibited_eku_present,Prohibited EKU(s) present: 1.3.6.1.5.5.7.3.2
certificate.tbsCertificate.extensions.5.extnValue.certificatePolicies,RequiredPolicyIdentifierValidator,ERROR,cabf.smime.no_required_reserved_policy_oid,Required policy OID 2.23.140.1.5.3.3 is missing
certificate.tbsCertificate.extensions.5.extnValue.certificatePolicies.0,CertificatePolicyQualifierValidator,NOTICE,pkix.certificate_policies_policy_has_qualifier,

