-----BEGIN CERTIFICATE-----
MIIGGDCCBACgAwIBAgIUSQDmcRlGl6fjul/gHkKTHkLQl2QwDQYJKoZIhvcNAQEL
BQAwSDELMAkGA1UEBhMCVVMxHzAdBgNVBAoMFkZvbyBJbmR1c3RyaWVzIExpbWl0
ZWQxGDAWBgNVBAMMD0ludGVybWVkaWF0ZSBDQTAeFw0yMzA0MTkwMDAwMDBaFw0y
MzA3MTgyMzU5NTlaMGQxDzANBgNVBAQMBllhbWFkYTEPMA0GA1UEKgwGSGFuYWtv
MRYwFAYDVQQDDA1ZQU1BREEgSGFuYWtvMSgwJgYJKoZIhvcNAQkBFhloYW5ha28u
eWFtYWRhQGV4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEAsPnoGUOnrpiSqt4XynxA+HRP7S+BSObI6qJ7fQAVSPtRkqsotWxQYLEYzNEx
5ZSHTGypibVsJylvCfuToDTfMul8b/CZjP2Ob0LdpYrNH6l5hvFE89FU1nZQF15o
VLOpUgA7wGiHuEVawrGfey92UE68mOyUVXGweJIVDdxqdMoPvNNUl86BU02vlBiE
SxOuox+dWmuVV7vfYZ79Toh/LUK43YvJh+rhv4nKuF7iHjVjBd9sB6iDjj70HFld
zOQ9r8SRI+9NirupPTkF5AKNe6kUhKJ1luB7S27ZkvB3tSTT3P593VVJvnzOjaA1
z6Cz+4+eRvcysqhrRgFlwI9TEwIDAQABo4IB3DCCAdgwDAYDVR0TAQH/BAIwADAO
BgNVHQ8BAf8EBAMCB4AwHwYDVR0jBBgwFoAU1kQAMnyoDf+sT2tm7rWumyzFOFQw
HQYDVR0OBBYEFIkZWV4O8Wn1y71H4TT84pjMaTCRMBQGA1UdIAQNMAswCQYHZ4EM
AQUEAjA9BgNVHR8ENjA0MDKgMKAuhixodHRwOi8vY3JsLmNhLmV4YW1wbGUuY29t
L2lzc3VpbmdfY2FfY3JsLmNybDBLBggrBgEFBQcBAQQ/MD0wOwYIKwYBBQUHMAKG
L2h0dHA6Ly9yZXBvc2l0b3J5LmNhLmV4YW1wbGUuY29tL2lzc3VpbmdfY2EuZGVy
MB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjCBtgYDVR0RBIGuMIGrgRlo
YW5ha28ueWFtYWRhQGV4YW1wbGUuY29toCkGCisGAQQBgjcUAgOgGwwZaGFuYWtv
LnlhbWFkYUBleGFtcGxlLmNvbaAmBggrBgEFBQcICaAaDBjlsbHnlLDoirHlrZBA
ZXhhbXBsZS5jb22kOzA5MQ8wDQYDVQQEDAblsbHnlLAxDzANBgNVBCoMBuiKseWt
kDEVMBMGA1UEAwwM5bGx55Sw6Iqx5a2QMA0GCSqGSIb3DQEBCwUAA4ICAQBXAbbb
yGLIBboQmz1d8XuWp37mMZtdSE+igZdsFmLu5mYrEflMQNw7S7m2sfuxt9Wrn/DC
YpZGscGaZ56oe8DNnv55fR1zOSFmk1YTeeTjnRbVnL8tQqv+PE55EDKbSTNTbUNX
KebH1+Us2nOjlVcN7z5jxPUKLDQ7bm2DFwMhxxV/WGiJQVbiLR8NucLHmk6s4m+r
4y9CUAm/ViGftgglox+YYY1xirSswYP9Ufvda1FwSX0/RnJAXo23yvWmRRpgu3ot
7BBC0iD43rpEKbXoCmLn/Zw8feefeD+MxyqRGfXC34JDrGzLcK9GNI1Dv9vCTQAV
H2hL8bsyCGl6dkS6Ipda0cSG6+pVzHKQWYeVYHV39/FZ6Z/E9t/zeIPnSjZecJUj
GMT5Pt1z38gFwkVsdL5y9I0uIMhMoUJ6Tx0ls+2CJ3s6Gt4CxljjDLK59gkjDmFd
cCfdVHxd3oequzWpB8k1k7+yYefQHElXibexphce9Sbmo2h5J24dVTznq9WlTzGP
JTF1eG9eyVyUsBe7CsrtmnY3/sWJOC1TviAO2bn7tcwrODzavxPHOHLeLwfbvSaG
VAaQVM2BQN5hokqKj0Vb6OFH3xIBUvKBCvzT5ct+NObTRfHjnTRtMtJyXbVKRvc4
VN7NZNIA6yv9HCYKwQDYzJLeSI1R7Hn0cw8S8Q==
-----END CERTIFICATE-----
node_path,validator,severity,code,message
certificate.tbsCertificate.extensions.3.extnValue.subjectKeyIdentifier,SubjectKeyIdentifierValidator,INFO,pkix.subject_key_identifier_method_1_identified,
certificate.tbsCertificate.extensions.4.extnValue.certificatePolicies,RequiredPolicyIdentifierValidator,ERROR,cabf.smime.no_required_reserved_policy_oid,Required policy OID 2.23.140.1.5.4.3 is missing
certificate.tbsCertificate.extensions.7.extnValue.extKeyUsageSyntax,AllowedExtendedKeyUsageValidator,ERROR,cabf.smime.prohibited_eku_present,Prohibited EKU(s) present: 1.3.6.1.5.5.7.3.2
certificate.tbsCertificate.extensions.8.extnValue.subjectAltName,SubjectAlternativeNameProhibitedGeneralNameTypesValidator,ERROR,cabf.smime.prohibited_othername_type_present,Prohibited otherName present: 1.3.6.1.4.1.311.20.2.3

